Support StartingDeadlineSeconds
AliyunContainerService/tf-operator pull request #14
Opened 2023-03-07 07:30 UTC by Syulin7

Specifies the duration (in seconds) since startTime during which the job can remain pending before it is terminated.

2023-03-07 07:58 UTC, cheyang requested changes

2023-03-07 07:58 UTC, cheyang commented on pkg/controller.v1/tensorflow/controller.go
> +		failureMessage = fmt.Sprintf("TFJob %s has failed because it was active longer than starting deadline", tfjob.Name)
I suggest using 

```golang
failureMessage := fmt.Sprintf("TFJob %s failed due to exceeding the starting deadline", tfjob.Name)
```

2023-03-08 06:52 UTC, Syulin7 commented on pkg/controller.v1/tensorflow/controller.go
> +		failureMessage = fmt.Sprintf("TFJob %s has failed because it was active longer than starting deadline", tfjob.Name)
Done

2023-03-08 09:06 UTC, cheyang commented
/lgtm
/approve

2023-03-08 09:06 UTC, cheyang approved these changes

2023-03-08 09:07 UTC, merged