Add successPolicy to TFJob
AliyunContainerService/tf-operator pull request #26
Opened 2024-09-20 03:20 UTC by ChenYi015

2024-09-20 03:23 UTC, ChenYi015 commented
CC @cheyang @happy2048 @Syulin7

2024-09-20 11:27 UTC, happy2048 commented on pkg/controller.v1/tensorflow/status.go
> +			if expected == 0 || (worker0Completed && *tfjob.Spec.SuccessPolicy != tfv1.SuccessPolicyAllWorkers) {
should make sure tfjob.Spec.SuccessPolicy is not null

2024-09-20 11:27 UTC, happy2048 commented on pkg/apis/tensorflow/v1/types.go
> +	SuccessPolicy *SuccessPolicy `json:"successPolicy,omitempty"`
can limit the successPolicy value by adding like: // +kubebuilder:validation:Enum=Lion;Wolf;Dragon?

2024-09-20 11:27 UTC, happy2048 commented on pkg/controller.v1/tensorflow/status.go
> +			if expected == 0 || (worker0Completed && *tfjob.Spec.SuccessPolicy != tfv1.SuccessPolicyAllWorkers) {
conditions: 
1. successPolicy == AllWorkers and:
    a. all workers are succeeded 
    b. at least one worker is failed
2. successPolicy != AllWorkers and:
    a.worker0 is succeeded
    b.worker0 is failed

2024-09-27 06:11 UTC, cheyang approved these changes
/lgtm
/approve

2024-09-29 07:11 UTC, cheyang requested changes

2024-09-29 07:11 UTC, cheyang commented on pkg/apis/tensorflow/v1/common.go
> +	SuccessPolicyChiefWorker SuccessPolicy = "ChiefWorker"
I suggest keep consistency with Kubeflow training operator.

2024-09-29 07:17 UTC, ChenYi015 commented on pkg/apis/tensorflow/v1/common.go
> +	SuccessPolicyChiefWorker SuccessPolicy = "ChiefWorker"
Done.

2024-09-29 09:09 UTC, cheyang approved these changes

2024-09-29 09:12 UTC, merged